/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bitirme.arayuz;

import bitirme.dao.AdminDao;
import bitirme.dao.KullaniciDao;
import bitirme.model.Admin;
import bitirme.model.Kullanici;
import bitirme.recog.Recog;
import bitirme.service.PropConfig;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_imgcodecs.imwrite;
import org.bytedeco.javacpp.opencv_videoio.*;
import static org.bytedeco.javacpp.opencv_videoio.CV_CAP_PROP_FRAME_HEIGHT;
import static org.bytedeco.javacpp.opencv_videoio.CV_CAP_PROP_FRAME_WIDTH;
import org.opencv.core.Core;

/**
 *
 * @author furkanb
 */
public class Main extends javax.swing.JFrame {

   /**
    * Creates new form Main
    */
   AdminDao ad;
   KullaniciDao kd = new KullaniciDao();

   CanliThread th = null;
   Mat fotograf = new Mat();
//   String database = null;
//   String fotografurl = database + "/test/test.jpg";

   String database = "/home/furkanb/Pictures/Webcam";

   String fotografurl = database + "/test/test.jpg";
   VideoCapture kamera = null;

   Recog recog = new Recog();

   class CanliThread implements Runnable {

      boolean calismaDurumu = false;

      @Override
      public void run() {

         while (calismaDurumu) {
            kamera.set(CV_CAP_PROP_FRAME_WIDTH, 640);
            kamera.set(CV_CAP_PROP_FRAME_HEIGHT, 480);

            kamera.grab();
            try {
               kamera.retrieve(fotograf);

               Thread.sleep(1000);
//            cvtColor(fotograf, fotograf, CV_LOAD_IMAGE_GRAYSCALE);
//            Imgcodecs.imencode(".jpg", fotograf, fotografBytes);
//            ByteBuffer bb = fotograf.asByteBuffer();
//            imencode(".jpg", fotograf, bb);
               imwrite(fotografurl, fotograf);

//               byte[] bytes = null;
//               imencode(".jpg", fotograf, bytes);
//               Image i2 = ImageIO.read(new ByteArrayInputStream(bytes));
//                       //InputStream,File,ImageInputStream
//               BufferedImage buff2 = (BufferedImage) i2;
               File sourceimage = new File(fotografurl);
               Image im = ImageIO.read(sourceimage);
               BufferedImage buff = (BufferedImage) im;

               Graphics g = panel.getGraphics();
               if (g.drawImage(buff, 0, 0, 640, 480, 0, 0, buff.getWidth(), buff.getHeight(), null)) {
                  if (calismaDurumu == false) {
                     System.out.println("durduruldu()");
                  }
               }

//               System.out.println(kd.getwId(recog.tanimla(database, fotografurl)).getAd());
               Kullanici k = kd.getwId(recog.tanimla(database, fotografurl));
//               cagir(k.getAd());
//               System.out.println("asdasdas" + k.getAd());
               tahmin.setText(k.getAd()+" "+k.getSoyad());
            } catch (Exception e) {
            }

         }

      }
   }
public void cagir(String k){
   System.out.println("cagrildi");
}
   public void urlYaz() {
      PropConfig pc = new PropConfig();

      database = pc.getDbName();
      System.out.println(pc.getDbName());
      fotografurl = database + "/test/test.jpg";
   }

   public Main() {
      urlYaz();

      ad = new AdminDao();
      initComponents();

      tahmin.setText("Tanimlanamadi");
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      panel = new javax.swing.JPanel();
      baslatBtn = new javax.swing.JButton();
      duraklatBtn = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      kadiTxt = new javax.swing.JTextField();
      girisBtn = new javax.swing.JButton();
      parolaTxt = new javax.swing.JPasswordField();
      tahmin = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

      javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
      panel.setLayout(panelLayout);
      panelLayout.setHorizontalGroup(
         panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 598, Short.MAX_VALUE)
      );
      panelLayout.setVerticalGroup(
         panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 405, Short.MAX_VALUE)
      );

      baslatBtn.setText("Başlat");
      baslatBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            baslatBtnActionPerformed(evt);
         }
      });

      duraklatBtn.setText("Duraklat");
      duraklatBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            duraklatBtnActionPerformed(evt);
         }
      });

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Admin Girişi"));

      jLabel1.setText("Kullanıcı Adı :");

      jLabel2.setText("Parola :");

      girisBtn.setText("Giriş");
      girisBtn.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            girisBtnActionPerformed(evt);
         }
      });

      parolaTxt.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            parolaTxtActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(girisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGap(18, 18, 18)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(kadiTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                     .addComponent(parolaTxt))))
            .addContainerGap())
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(kadiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(parolaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(girisBtn)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      tahmin.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
      tahmin.setText("jLabel3");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(baslatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(duraklatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(tahmin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(tahmin)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(baslatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(duraklatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(8, 8, 8)))
            .addContainerGap(44, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void baslatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslatBtnActionPerformed
      kamera = new VideoCapture(0);
      //sistemdeki kameraları 0,1,2

      th = new Main.CanliThread();

      Thread t = new Thread(th);
      t.setDaemon(true);
      //threadi çalıştır
      th.calismaDurumu = true;

      t.start();
      baslatBtn.setEnabled(false);  //start button
      duraklatBtn.setEnabled(true);  // stop button
   }//GEN-LAST:event_baslatBtnActionPerformed

   private void duraklatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duraklatBtnActionPerformed
      th.calismaDurumu = false;
      duraklatBtn.setEnabled(false);
      baslatBtn.setEnabled(true);

      kamera.release();
   }//GEN-LAST:event_duraklatBtnActionPerformed

   private void girisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisBtnActionPerformed
      Admin a = new Admin();
      a.setKAdi(kadiTxt.getText());
      a.setKParola(parolaTxt.getText());

      if (ad.girisKontrol(a) == null) {
         System.out.println("giriş yapılmadı");
      } else {
         new AdminMain().show();
      }
   }//GEN-LAST:event_girisBtnActionPerformed

   private void parolaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parolaTxtActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_parolaTxtActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Main().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton baslatBtn;
   private javax.swing.JButton duraklatBtn;
   private javax.swing.JButton girisBtn;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JTextField kadiTxt;
   private javax.swing.JPanel panel;
   private javax.swing.JPasswordField parolaTxt;
   private javax.swing.JLabel tahmin;
   // End of variables declaration//GEN-END:variables
}
